POST http://localhost:4000/todos
Content-Type: application/json

{
    "title": "My second todo",
    "description": "I will code my nigga",
    "deadline": "2023-7-13"
}

### get all todos

GET http://localhost:4000/todos
Content-Type: application/json

### get one todo
GET http://localhost:4000/todos/a1e7b9c6-a7eb-4786-a24c-0b05d1b65e12
Content-Type: application/json

### updating the todo
PUT http://localhost:4000/todos/a1e7b9c6-a7eb-4786-a24c-0b05d1b65e12
Content-Type: application/json

{
    "title": "My first todo UPDATED",
    "description": "This is what I will do ",
    "deadline": "2023-7-13"
}

### deleting a todo
DELETE http://localhost:4000/todos/a1e7b9c6-a7eb-4786-a24c-0b05d1b65e12
Content-Type: application/json

### Mark todo as done
PUT http://localhost:4000/todos/complete/a1e7b9c6-a7eb-4786-a24c-0b05d1b65e12
Content-Type: application/json



### Creating a user
POST http://localhost:4000/users/createuser
Content-Type: application/json

{
    "email": "dankinyi99@gmail.com",
    "password": "12345678"
}

### User login
POST http://localhost:4000/users/login
Content-Type: application/json

{
    "email": "gamesmy177@gmail.com",
    "password": "12345678"
}