POST http://localhost:4000/todos
Content-Type: application/json

{
    "title": "My fifth todo",
    "description": "This is what I will do",
    "deadline": "2023-7-13"
}

### get all todos

GET http://localhost:4000/todos
Content-Type: application/json

### get one todo
GET http://localhost:4000/todos/2937d9c2-ff76-4781-9a97-8d200ddd45d5
Content-Type: application/json

### updating the todo
PUT http://localhost:4000/todos/2937d9c2-ff76-4781-9a97-8d200ddd45d5
Content-Type: application/json

{
    "title": "My third todo UPDATED",
    "description": "This is what I will do ",
    "deadline": "2023-7-13"
}

### deleting a todo
DELETE http://localhost:4000/todos/08bb3db6-7470-463f-8b30-90c332f9ab73
Content-Type: application/json

### Mark todo as done
PUT http://localhost:4000/todos/complete/3d54d319-3b8e-4062-a578-fec33f4f42c2
Content-Type: application/json